### PR TITLE
Refactor vscode extension

### PR DESCRIPTION
**Pull request by aochagavia**
Todo:

- [x] Add more comments, so other people can find their way in the codebase
- [x] Resolve remaining tslint suggestions
- [ ] Integrate with CI

@matklad The standard configuration of tslint forbids using `console.log` and `console.error`. Is there any reason we are using those or can I remove them? If they are used for debugging purposes I would prefer to remove them and rely on vscode's excellent debugger.

### CODE REVIEW

**Comment by matklad** [comment]
Looks awesome, thank you so much for all these!

>can I remove them? 

I think you can remove them, yes!

**Comment by matklad** [comment]
I'll go ahead and r+ this as is, because it already is way better than what we've had previously.

bors r+

**Comment by aochagavia** [comment]
Sorry, it looks like my commit interrupted bors...

For the CI integration we can look at other language servers, like sourcegraph's [typescript](https://github.com/sourcegraph/javascript-typescript-langserver) one.

We need to adapt the current `appveyor.yml` to:

1. Install node and npm
1. Try to bulid the extension
1. Check the extension against tslint
1 Cache npm packages as they do in the typescript language server.

I don't know exactly how to do this, so if anyone knows it already feel free to implement it... Otherwise I will figure it out later.

**Comment by matklad** [comment]
@aochagavia added you to the reviewers list. Could you try r+ this PR?

**Pull request merged**
