### PR TITLE
Add a setting to disable custom syntax highlighting

### PR DESCRIPTION
**Pull request by aochagavia**

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Thanks!

**Comment by aochagavia** [comment]
It looks like the configuration is loaded when the extension is initalized, so changes to it do not reflect until a restart. We could better check the configuration each time `setHighlights` is called. I'll push a new commit to address this.

**Comment by aochagavia** [comment]
Hmm the extension works in a different way than I expected... Checking each time the `setHighlights` is called does not help... @matklad If you don't mind, I would like to open an issue so I remember to fix this later (I don't have the time right now to figure vscode's extensions API).

**Comment by matklad** [comment]
Sure, do open an issue!

I think checking at `setHighlights` is one part of a solution, but we should also call set highlights with empty decorations when the setting changes, so that we clear all existing ones .

**Pull request merged**
