### PR TITLE
libsyntax2 -> rust-analyzer

### PR DESCRIPTION
**Pull request by kjeremy**
Change a few `libsyntax2` to `rust-analyzer`

### CODE REVIEW

**Comment by matklad** [comment]
bors r+

Thanks!

**Comment by matklad** [comment]
bors r+

?

**Comment by notriddle** [comment]
@matklad Any idea why AppVeyor isn't building anything?

**Comment by matklad** [comment]
@notriddle no idea :(

I've recently renamed the repo though, this sounds like it might be the issue.

**Pull request merged**
